Algoritmo "dados_entrada"

Var

   idade : inteiro
   salario1, salario2 : real
   nome:caractere
   
Inicio

   escreva("Digite se nome: ")
   leia(nome)
   escreva("Digite sua idade: ")
   leia(idade)
   escreval("Digite quanto voce ganhou nos dois ultimos meses: ")
   leia(salario1)
   leia(salario2)
   
   escreval ("DADOS DIGITADOS")
   escreval("Nome = ", nome)
   escreval("Idade = ", idade)
   escreval("Salario1 = ", salario1)
   escreval("Salario2 = ", salario2)
   
Fimalgoritmo